name = "sameday025"
main = "server/index.ts"
compatibility_date = "2024-01-15"

[env.production]
name = "sameday025-production"
routes = [
  { pattern = "sameday025.com/*", zone_name = "sameday025.com" },
  { pattern = "www.sameday025.com/*", zone_name = "sameday025.com" }
]

[[env.production.vars]]
NODE_ENV = "production"

[build]
command = "npm run build"
cwd = "."
watch_dir = "client"

[[pages_build_output_dir]]
output_dir = "dist"